---
language: ruby
cache: bundler
rvm:
  - 2.4.0
  - 2.5.0
  - 2.6.0
  - 2.7.0
  - ruby-head
before_install:
  - yes | gem update --system --force
  - gem install bundler
jobs:
  include:
  - rvm: jruby-head
    before_install:
      - bundle install rake -v 13.0.0
