---
language: ruby
cache: bundler
install: bundle install --jobs=3 --retry=3
rvm:
  - 2.5
  - 2.6
  - 2.7
  - 3.0
  - ruby-head
before_install: gem install bundler -v '~>2.0'
jobs:
  include:
  - rvm: 2.4
    before_install:
      - yes | gem update --system --force
      - gem install bundler
  - rvm: jruby-head
    before_install:
      - bundle add rake --version "13.0.0"
